2021-08-04 19:31:09,073 ERROR: Exception on /auth/reset_password_request [POST] [in C:\Users\Administrator\.virtualenvs\microblog\lib\site-packages\flask\app.py:1455]
Traceback (most recent call last):
  File "C:\Users\Administrator\.virtualenvs\microblog\lib\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Administrator\.virtualenvs\microblog\lib\site-packages\flask\app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Administrator\.virtualenvs\microblog\lib\site-packages\flask\app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Administrator\.virtualenvs\microblog\lib\site-packages\flask\app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "E:\python\PyCharmWork\microblog\app\auth\routes.py", line 79, in reset_password_request
    send_password_reset_email(user)
  File "E:\python\PyCharmWork\microblog\app\auth\email.py", line 35, in send_password_reset_email
    user=user, token=token),
  File "C:\Users\Administrator\.virtualenvs\microblog\lib\site-packages\flask\templating.py", line 150, in render_template
    ctx.app,
  File "C:\Users\Administrator\.virtualenvs\microblog\lib\site-packages\flask\templating.py", line 128, in _render
    rv = template.render(context)
  File "C:\Users\Administrator\.virtualenvs\microblog\lib\site-packages\jinja2\environment.py", line 1304, in render
    self.environment.handle_exception()
  File "C:\Users\Administrator\.virtualenvs\microblog\lib\site-packages\jinja2\environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "E:\python\PyCharmWork\microblog\app\templates\email\reset_password.txt", line 5, in top-level template code
    {{ url_for('reset_password', token=token, _external=True) }}
  File "C:\Users\Administrator\.virtualenvs\microblog\lib\site-packages\flask\helpers.py", line 338, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "C:\Users\Administrator\.virtualenvs\microblog\lib\site-packages\flask\helpers.py", line 326, in url_for
    endpoint, values, method=method, force_external=external
  File "C:\Users\Administrator\.virtualenvs\microblog\lib\site-packages\werkzeug\routing.py", line 2305, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'reset_password' with values ['token']. Did you mean 'auth.reset_password' instead?
2021-08-04 19:33:04,495 INFO: Microblog startup [in E:\python\PyCharmWork\microblog\app\__init__.py:64]
2021-08-04 19:33:09,138 ERROR: Exception on /auth/reset_password_request [POST] [in C:\Users\Administrator\.virtualenvs\microblog\lib\site-packages\flask\app.py:1455]
Traceback (most recent call last):
  File "C:\Users\Administrator\.virtualenvs\microblog\lib\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Administrator\.virtualenvs\microblog\lib\site-packages\flask\app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Administrator\.virtualenvs\microblog\lib\site-packages\flask\app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Administrator\.virtualenvs\microblog\lib\site-packages\flask\app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "E:\python\PyCharmWork\microblog\app\auth\routes.py", line 79, in reset_password_request
    send_password_reset_email(user)
  File "E:\python\PyCharmWork\microblog\app\auth\email.py", line 35, in send_password_reset_email
    user=user, token=token),
  File "C:\Users\Administrator\.virtualenvs\microblog\lib\site-packages\flask\templating.py", line 150, in render_template
    ctx.app,
  File "C:\Users\Administrator\.virtualenvs\microblog\lib\site-packages\flask\templating.py", line 128, in _render
    rv = template.render(context)
  File "C:\Users\Administrator\.virtualenvs\microblog\lib\site-packages\jinja2\environment.py", line 1304, in render
    self.environment.handle_exception()
  File "C:\Users\Administrator\.virtualenvs\microblog\lib\site-packages\jinja2\environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "E:\python\PyCharmWork\microblog\app\templates\email\reset_password.txt", line 5, in top-level template code
    {{ url_for('reset_password', token=token, _external=True) }}
  File "C:\Users\Administrator\.virtualenvs\microblog\lib\site-packages\flask\helpers.py", line 338, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "C:\Users\Administrator\.virtualenvs\microblog\lib\site-packages\flask\helpers.py", line 326, in url_for
    endpoint, values, method=method, force_external=external
  File "C:\Users\Administrator\.virtualenvs\microblog\lib\site-packages\werkzeug\routing.py", line 2305, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'reset_password' with values ['token']. Did you mean 'auth.reset_password' instead?
2021-08-04 19:33:19,588 INFO: Microblog startup [in E:\python\PyCharmWork\microblog\app\__init__.py:64]
2021-08-04 19:33:27,348 ERROR: Exception on /auth/reset_password_request [POST] [in C:\Users\Administrator\.virtualenvs\microblog\lib\site-packages\flask\app.py:1455]
Traceback (most recent call last):
  File "C:\Users\Administrator\.virtualenvs\microblog\lib\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Administrator\.virtualenvs\microblog\lib\site-packages\flask\app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Administrator\.virtualenvs\microblog\lib\site-packages\flask\app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Administrator\.virtualenvs\microblog\lib\site-packages\flask\app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "E:\python\PyCharmWork\microblog\app\auth\routes.py", line 79, in reset_password_request
    send_password_reset_email(user)
  File "E:\python\PyCharmWork\microblog\app\auth\email.py", line 35, in send_password_reset_email
    user=user, token=token),
  File "C:\Users\Administrator\.virtualenvs\microblog\lib\site-packages\flask\templating.py", line 150, in render_template
    ctx.app,
  File "C:\Users\Administrator\.virtualenvs\microblog\lib\site-packages\flask\templating.py", line 128, in _render
    rv = template.render(context)
  File "C:\Users\Administrator\.virtualenvs\microblog\lib\site-packages\jinja2\environment.py", line 1304, in render
    self.environment.handle_exception()
  File "C:\Users\Administrator\.virtualenvs\microblog\lib\site-packages\jinja2\environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "E:\python\PyCharmWork\microblog\app\templates\email\reset_password.txt", line 5, in top-level template code
    {{ url_for('reset_password', token=token, _external=True) }}
  File "C:\Users\Administrator\.virtualenvs\microblog\lib\site-packages\flask\helpers.py", line 338, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "C:\Users\Administrator\.virtualenvs\microblog\lib\site-packages\flask\helpers.py", line 326, in url_for
    endpoint, values, method=method, force_external=external
  File "C:\Users\Administrator\.virtualenvs\microblog\lib\site-packages\werkzeug\routing.py", line 2305, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'reset_password' with values ['token']. Did you mean 'auth.reset_password' instead?
2021-08-04 19:34:01,244 INFO: Microblog startup [in E:\python\PyCharmWork\microblog\app\__init__.py:64]
2021-08-04 19:45:40,707 INFO: Microblog startup [in E:\python\PyCharmWork\microblog\app\__init__.py:64]
2021-08-04 20:00:23,398 INFO: Microblog startup [in E:\python\PyCharmWork\microblog\app\__init__.py:64]
2021-08-05 14:14:13,760 INFO: Microblog startup [in E:\python\PyCharmWork\microblog\app\__init__.py:64]
2021-08-05 16:23:21,638 INFO: Microblog startup [in E:\python\PyCharmWork\microblog\app\__init__.py:64]
